### ISSUE TITLE
Docker Container Exited (1) on Unraid 6.11.5

### ISSUE THREAD

**Issue by eroc1990** [mattwebbio/orbital-sync#116]
EDIT I'm an idiot and need to pay attention when I type.

**Comment by mattwebbio** [comment]
Hi @eroc1990! I see you've closed the issue. For my own knowledge, would you mind sharing what the issue was?

**Comment by eroc1990** [comment]
I mistyped PRIMARY_HOST_BASE_URL and, as a result, Orbital couldn't launch. That was my only issue 😂
