### ISSUE TITLE
Support passwordless pihole installations

### ISSUE THREAD

**Issue by saua** [mattwebbio/orbital-sync#179]
### What feature would you like added?

Would you consider supporting pihole installations that have no password set?

My pihole is running inside a docker container and outside access to its web UI is handled via a Traefik proxy which also handles authorization (i.e. there is no unauthorized access). To avoid unnecessary "double-authentication" I disabled the password in pihole itself.

This would also mean that orbital-sync running inside docker could directly access the web UI without a password (bypassing Traefik).

The *secondary* pihole(s) would then be running on another host, and *would* be using passwords (arbitrarily complex ones, since a real user would never need to enter them).

In theory one could also run the secondary ones passwordless and just never expose their web UI to a (non-docker-internal) network at all, in that case the primary one should be password protected. That's not *my* usecase, but that could also be enabled via this feature.

Unfortunately I didn't find a way to configure this and a quick peek at the code suggests that it's not intended (I did a few minor experiments to see if I could hack this together myself, but didn't get anywhere).

**Comment by Ramias1** [comment]
This just worked fine for me with PiHole 1 and PiHole 2 both running password less.  Just configure like this.

`PRIMARY_HOST_PASSWORD: ''`

**Comment by conceptual-perception** [comment]
I've implemented this using

`PRIMARY_HOST_PASSWORD: ''`

If this isn't intended, let me know, otherwise, it's working so far!

**Comment by saua** [comment]
Sorry, I can confirm that this works as mentioned above. I don't know why this didn't work for me previously. I probably mis-configured something else when I tried that.
