### ISSUE TITLE
 SMTP is misconfigured

### ISSUE THREAD

**Issue by djonepl** [mattwebbio/orbital-sync#193]
### What happened?

      Hi, great piece of software, works very well. 
      
      Im having an issue with notifications. Its telling me the SMTP is misconfigured. Not sure what am i missing.
      Thanks. 

      SMTP_HOST: 10.30.0.54
      SMTP_PORT: 32768
      SMTP_FROM: from@domain.com
      SMTP_TO: to@domain.com
      NOTIFY_ON_SUCCESS: true
      NOTIFY_ON_FAILURE: true
      NOTIFY_VIA_SMTP: true
      TZ: America/New_York

### Version

latest

### Log output

```shell
12/13/2023, 8:53:34 PM: ✔️ Success: 1/1 hosts synced.
12/13/2023, 8:53:34 PM: ⚠ Error: SMTP is misconfigured. Please check your configuration.
12/13/2023, 8:53:34 PM: Waiting 30 minutes...
```

**Comment by coldshouldermedia** [comment]
I have a similar issue.  I've got Orbital Sync pointing at my mailrise, and my sync completes, but I get the same `⚠ Error: SMTP is misconfigured. Please check your configuration.` error.

Did you every figure out the problem?

**Comment by djonepl** [comment]
Unfortunately I haven't. I briefly looked through the source but its above my pay grade ;) Works great otherwise.

**Comment by alexsantos89** [comment]
Not sure it is exactly the same problem, but I was experiencing problems too using an SMTP server without authentication and I manually modified the code to ignore the property "auth" in case no SMTP_USER was provided, edited the file notify.js:

ORIGINAL:
`auth:       {
                      user: Config.smtpUser,
                      pass: Config.smtpPassword
                    }`


MODIFIED
`auth: Config.smtpUser 
                  ? {
                      user: Config.smtpUser,
                      pass: Config.smtpPassword
                    }
                  : undefined`

@mattwebbio what do you think about this change, could we merge this code to master (I could try to open a pull request)? (I love your software by the way, really useful, great work!)

**Comment by mattwebbio** [comment]
> @mattwebbio what do you think about this change, could we merge this code to master (I could try to open a pull request)? (I love your software by the way, really useful, great work!)

Sorry for the delayed response - very little time for OSS, unfortunately. Create a PR and if the tests pass, I'll release :)

**Comment by alexsantos89** [comment]
> > @mattwebbio what do you think about this change, could we merge this code to master (I could try to open a pull request)? (I love your software by the way, really useful, great work!)
> 
> Sorry for the delayed response - very little time for OSS, unfortunately. Create a PR and if the tests pass, I'll release :)

Thanks for replying. Looks like this repo does not accept PR: 
`Can't create a new pull request: Push failed: remote: Permission to mattwebbio/orbital-sync.git denied to alexsantos89. unable to access 'https://github.com/mattwebbio/orbital-sync.git/': The requested URL returned error: 403`

You could add me as a contributor or change the portion of code yourself, small change, whatever you prefer. Thank you!!!

<img width="1075" alt="Screenshot 2024-01-29 at 23 08 16" src="https://github.com/mattwebbio/orbital-sync/assets/10471730/08dab698-3143-4bb1-89a7-0dc07c6df07a">

**Comment by Impact123** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by mattwebbio** [comment]
Thanks for the PR, @alexsantos89! 🥳

Release just completed for 1.5.3

**Comment by coldshouldermedia** [comment]
Sadly my `⚠ Error: SMTP is misconfigured. Please check your configuration.` persists.

**Comment by mattwebbio** [comment]
@coldshouldermedia 
> Sadly my `⚠ Error: SMTP is misconfigured. Please check your configuration.` persists.

Two things:
1. I broke release (😅); as a result, the newest release to have the fix is `1.5.7`, which was only released a few minutes ago. Try that one.
2. If that doesn't fix, could you share an example of your configuration [like the OP did](https://github.com/mattwebbio/orbital-sync/issues/193#issue-2040772456)? OP's issue was that there was no username/password, so if your misconfiguration is due to a different issue an example of your config would help narrow down the cause

**Comment by coldshouldermedia** [comment]
1. Yeah, [that was my issue!](https://github.com/mattwebbio/orbital-sync/issues/227) 😃 Just deleted all orbital-sync images and repulled.  Portainer reports version 1.5.7
2. The commented lines are the configurations I've tried enabling, just in case.  For reference, I'm using [mailrise](https://github.com/YoRyan/mailrise) for local smtp handling.  Did I bungle something?
```
      TZ: America/Denver
      NOTIFY_ON_SUCCESS: true
      NOTIFY_ON_FAILURE: true
      NOTIFY_VIA_SMTP: true
      #SMTP_TLS: false
      SMTP_HOST: 192.168.1.111
      SMTP_PORT: 8025
      #SMTP_USER: admin@cloud.local
      #SMTP_FROM: admin@cloud.local
      SMTP_TO: orbital-sync@mailrise.xyz
```

**Comment by mattwebbio** [comment]
Oops, my bad :smile:

Try running with `VERBOSE: true` - is there any additional error info?

**Comment by coldshouldermedia** [comment]
One additional line with VERBOSE enabled:
`2/1/2024, 2:33:48 PM: connect EHOSTUNREACH 192.168.1.111:8025`
