### ISSUE TITLE
Unable to sync third secondary pihole

### ISSUE THREAD

**Issue by mike12806** [mattwebbio/orbital-sync#195]
### What happened?

I have 4 piholes, 1 primary and 3 secondary piholes. Whenever I had docker env variables for a 3rd secondary host, it's ignored by orbital sync and only the primary and first 2 secondary piholes are synced. 

The issue occurs when adding the env variables:
```
SECONDARY_HOST_3_BASE_URL
SECONDARY_HOST_3_PASSWORD
```

### Version

1.5.2

**Comment by mike12806** [comment]
Hey @mattwebbio  - any thoughts here?

**Comment by mattwebbio** [comment]
This smells like misconfiguration to me, but it's difficult to prove with the small amount of information you've provided. If you share more info (i.e. full configuration, verbose logs), I or someone in the community might be able to help - but there are tests in the code that test this configuration type and they all pass.
