### ISSUE TITLE
Group management status not synchronized to second pi-hole

### ISSUE THREAD

**Issue by rbrtdvd** [mattwebbio/orbital-sync#196]
### What happened?

In the list of groups there's one group defined (exclude_from_pihole) on the main pi-hole.

The group is nicely synchronized to the secondary pi-hole (pi-hole2). However when I disable that group on the main pi-hole, it does not get synchronized to the secondary pi-hole. The group stays enabled.

When I disable the group manually on the secondary pi-hole, it's automatically enabled again after synchronization (even though on the main pi-hole it's also disabled).

### Version

orbital-sync:1 (18.15.0)

**Comment by snazy2000** [comment]
Looks like thats a bug with Pihole itself as the backup file contains a file called groups.json which what I just tested (disabling kids group) it still said enabled
