### ISSUE TITLE
Update "latest" tag on Docker Hub

### ISSUE THREAD

**Issue by coldshouldermedia** [mattwebbio/orbital-sync#227]
### What happened?

The new version is out, and while going to pull the new image from docker hub, I saw that it's not tagged as the `latest` version.

https://hub.docker.com/r/mattwebbio/orbital-sync/tags

### Version

1.5.2

**Comment by B0rax** [comment]
On that note, the docker-compose script in the readme refers to the tag 1. maybe it is a good idea to update that to latest as well.

**Comment by mattwebbio** [comment]
@B0rax 
> On that note, the docker-compose script in the readme refers to the tag 1. maybe it is a good idea to update that to latest as well.

That's already covered; the workflow is configured to tag every new minor and patch image as `1` provided its major version is still `1`:
https://github.com/mattwebbio/orbital-sync/blob/e496c31ff87cdfc9579a6cdac0bd78b10999a8fd/.github/workflows/perform-release.yml#L44

In other words, the only way to lock to a specific minor version is to use `mattwebbio/orbital-sync:1.5` and the only way to lock to a specific patch version is to use `mattwebbio/orbital-sync:1.5.7`.

**Comment by mattwebbio** [comment]
All the appropriate image tags were updated as of `1.5.7`! Thanks for the report 🙂
