### ISSUE TITLE
Additional notification options

### ISSUE THREAD

**Issue by mentalsoup** [mattwebbio/orbital-sync#26]
### What feature would you like added?

I would like to be able to send sync notifications for success/failure of orbital-sync to either/or:
Telegram chat group
Gotify server

### Version

1.1.1 (latest)

**Comment by mattwebbio** [comment]
Would the idea be to get success/failure notifications every interval a sync is performed? 

If you use the default interval of 30 mins, this could generate a lot of noise. It might make more sense to only alert upon failure?

**Comment by mentalsoup** [comment]
Fair comment, I agree that would get irritating. Alert on failure only by default perhaps. Then those that want the noise can manage it themselves.

**Comment by mattwebbio** [comment]
Sorry for the delay on this, I haven't had a lot of time and wanted to refactor some of the error handling to make handling notifications easier in the future. 

I have a beta tag for the container image that adds SMTP email notification support: `mattwebbio/orbital-sync:1.1.3-beta.0`
The documentation for configuring it is available here: https://github.com/mattwebbio/orbital-sync/blob/7ec6205259731cdddd9184dcf6cda161e320f1b6/README.md#notifications

How important do you feel is support for other services such as Telegram or Gotify? I've not used either of those personally.

**Comment by mentalsoup** [comment]
No issue on the timescale, take it at your own pace.
I do not consider either Telegram or Gotify essential. If you are happy with email notifications, then that's fine.
An alternative to direct integration with any system could be to execute a script if an error occurs, then you could leave it up to the user regarding their chosen method of notification.

**Comment by mattwebbio** [comment]
I've just merged and released SMTP as part of `1.2`. Let me know if you have any issues with it :)
