### ISSUE TITLE
Gravity Sync

### ISSUE THREAD

**Issue by mentalsoup** [mattwebbio/orbital-sync#28]
### What feature would you like added?

Based upon a fresh instance of pihole on both docker tenants.

***Feature***

Once the teleport completes successfully, then trigger gravity sync on the secondary pihole.

***Observations***

I noticed that after a successful sync between master and secondary pihole tenants, the adlists on the secondary did not appear to be downloaded.

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

<html><body>

Health status of this list: | List was not downloaded so far
-- | --
This list was added to Pi-hole | 2 hours ago (2022-09-14 19:34:54)
Database entry was last modified | 8 minutes ago (2022-09-14 21:51:22)
The list contents were last updated | N/A
Number of domains on this list: | N/A
Number of invalid domains on this list: | N/A
Database ID of this list: | 1

</body>
</html> 

### Version

1.1.1 (latest)

**Comment by mattwebbio** [comment]
Ah, great catch! Thanks for this. I was hoping the teleporter would automatically take care of this but I guess not. I'll look into this further and see what's involved in making sure this gets run

**Comment by mentalsoup** [comment]
I will test further as I have been hit by the permission issues in docker pihole, took a while to figure that one out. This manifested in failures to write to the adlist on the dB. Setting env WEB_UID to the container's pihole user resolved it. For now at least.
So this issue might be false, I will try to confirm.

**Comment by mentalsoup** [comment]
The issue stills stands for me. I added a new item to the adlist on the primary.
Restarted orbital-sync.
Waited for the sync to complete.
The new item appeared in the adlist on the secondary pihole, but the status of all items shows as above in my original post.

Manually triggering an update of gravity refreshes without an issue.

**Comment by mattwebbio** [comment]
@mentalsoup I've published a beta version of the container that should resolve this. The image has been published as: [`mattwebbio/orbital-sync:1.2.2-beta.0`](https://hub.docker.com/layers/mattwebbio/orbital-sync/1.2.2-beta.0/images/sha256-a8aab7b145ad03e483a3a46b3ba03998dd4c7a7ce0baa4eba520e276ab9adbd6?context=explore)

If at some point you have the time to try it, I'd love to hear if it works for you 😄

**Comment by mentalsoup** [comment]
Thanks @mattwebbio, great work. I have updated to [mattwebbio/orbital-sync:1.2.2-beta.0](https://hub.docker.com/layers/mattwebbio/orbital-sync/1.2.2-beta.0/images/sha256-a8aab7b145ad03e483a3a46b3ba03998dd4c7a7ce0baa4eba520e276ab9adbd6?context=explore) and the sync has completed successfully on both targets. No errors, but this has spawned a new idea, I will raise a new feature request.
I am going to switch back to the latest image and await the update from there.

**Comment by mattwebbio** [comment]
Perfect! I've gone ahead and released version `1.3` of the container with this change 🙂
