### ISSUE TITLE
Provide TZ as environment variable

### ISSUE THREAD

**Issue by mentalsoup** [mattwebbio/orbital-sync#29]
### What feature would you like added?

It would be useful to be able to set the timezone so that log date time stamps align to the given region.
If this could be defined on the environment collection, that would be ideal.

***Example***

environment:
      - TZ=Europe/London

### Version

1.1.2

**Comment by mattwebbio** [comment]
This already works because the Docker container is based off of `node:18`, but it's not in the README. I'll update it to include this.
