### ISSUE TITLE
Different env variables name

### ISSUE THREAD

**Issue by RiKap** [mattwebbio/orbital-sync#342]
### What happened?

Hey,
based on configuration file I should use `NOTIFY_SMTP_ENABLED`, `NOTIFY_SMTP_FROM`, ..., but based on `schema.ts`, it is `SMTP_ENABLED`, `SMTP_FROM`, ....

So there is a configuration mismatch as it contains a redundant `NOTIFY_` prefix. It happened in this commit https://github.com/mattwebbio/orbital-sync/commit/cb622b334f4fd6fe4fdaa6e575b1f9b0e99cfb68

### Version

master, [v1.7.0](https://github.com/mattwebbio/orbital-sync/releases/tag/v1.7.0), [v1.8.0](https://github.com/mattwebbio/orbital-sync/releases/tag/v1.8.0), [v1.8.1](https://github.com/mattwebbio/orbital-sync/releases/tag/v1.8.1)

**Comment by mattwebbio** [comment]
The environment variables listed on the [Configuration page](https://orbitalsync.com/CONFIG.html) are the new ones that should be used. The ones explicitly listed in `schema.ts` are from an older version and have just been kept for backwards compatibility :)
