### ISSUE TITLE
Use of orbital-sync stops/interrupts stat collection on the primary PiHole instance

### ISSUE THREAD

**Issue by lmorgan-yozu** [mattwebbio/orbital-sync#381]
### What happened?

I spun up Orbital-Sync earlier today and since the container has been running/syncing (which it does great, thanks!), I've experienced an issue with stats on the primary PiHole. It seems that every time the sync happens the stats on the primary PiHole get reset. I've rebooted the primary PiHole container (rule #1), issue persisted. 

Other than that I've confirmed as much as I'm able to at this point by stopping the orbital-sync container, and stat collection has returned to normal. I'm not sure if this is normal behaviour (i.e. a side-effect of the teleport backup orbital-sync uses), but it would be great if it could be fixed.

No errors or issues are shown in the orbital-sync logs (attached), nor anything out of the ordinary on the PiHole so far as I can see.

Attached a couple of images (neither very helpful), the latter showing some other strange behaviour I've picked up on - with the PiHole API on the primary node now giving corrupted/unparseable stats via the API to Homepage (gethomepage.dev). 

(This weird API behaviour persists even after stopping orbital-sync, which makes me worry there might be some sort of corruption caused in the stats).

![image](https://github.com/user-attachments/assets/b07ed3f9-b9f5-49ff-b291-973014fdd4fd)
![image](https://github.com/user-attachments/assets/b7c5b527-973e-47f7-b5e1-614727a686a7)

### Version

mattwebbio/orbital-sync:1

### Log output

```shell
7/27/2024, 7:40:16 PM: Waiting 5 minutes...
7/27/2024, 7:45:16 PM: ➡️ Signing in to https://pihole.mydomain.io/admin...
7/27/2024, 7:45:16 PM: ✔️ Successfully signed in to https://pihole.mydomain.io/admin!
7/27/2024, 7:45:16 PM: ➡️ Downloading backup from https://pihole.mydomain.io/admin...
7/27/2024, 7:45:17 PM: ✔️ Backup from https://pihole.mydomain.io/admin completed!
7/27/2024, 7:45:17 PM: ➡️ Signing in to https://pihole2.mydomain.io/admin...
7/27/2024, 7:45:17 PM: ✔️ Successfully signed in to https://pihole2.mydomain.io/admin!
7/27/2024, 7:45:17 PM: ➡️ Uploading backup to https://pihole2.mydomain.io/admin...
7/27/2024, 7:45:18 PM: ✔️ Backup uploaded to https://pihole2.mydomain.io/admin!
7/27/2024, 7:45:18 PM: ➡️ Updating gravity on https://pihole2.mydomain.io/admin...
7/27/2024, 7:45:19 PM: ✔️ Gravity updated on https://pihole2.mydomain.io/admin!
7/27/2024, 7:45:19 PM: ✔️ Success: 1/1 hosts synced.
7/27/2024, 7:45:19 PM: Waiting 5 minutes...
```

**Comment by mattwebbio** [comment]
Unfortunately, this is probably an issue with the way Pi-hole handles the restoration of backups (remember, all Orbital Sync is doing is restoring a backup from another Pi-hole)

I'm going to close this issue as changes to this behavior would probably need to happen in Pi-hole itself.
