### ISSUE TITLE
Heading "Configuration" link on https://orbitalsync.com/CONFIG.html links to 404 https://orbitalsync.com/CONFIGURATION.html

### ISSUE THREAD

**Issue by timtjtim** [mattwebbio/orbital-sync#389]
### What happened?

Issue with the documentation - the heading link "Configuration" https://orbitalsync.com/CONFIG.html links to 404 https://orbitalsync.com/CONFIGURATION.html

It should just link to https://orbitalsync.com/CONFIG.html or an anchor like `#`

### Version

-

**Comment by mattwebbio** [comment]
Closed by #390
