### ISSUE TITLE
Allow paths to pi-hole that don't contain /admin

### ISSUE THREAD

**Issue by cbundy** [mattwebbio/orbital-sync#62]
### What feature would you like added?

Hello,

My main pi-hole is reachable at something like https://mydomain.com/pihole. Because it's behind a reverse proxy, I ended up hiding the /admin part of the path. 

I've built my own version now that has removed it, I can make a PR with a configuration option that allows more control over the URL if you think this would be a welcome addition.

### Version

latest

**Comment by mattwebbio** [comment]
Hi! I would gladly accept a pull request for this. I think the best approach might be to add optional `PRIMARY_HOST_PATH` and `SECONDARY_HOST_(#)_PATH` options that default to `/admin`. How do you feel about this?

The other option could be to replace `PRIMARY_HOST_BASE_URL` with a singular `PRIMARY_HOST_URL` that includes the path (i.e. `http://10.0.0.2/admin`), but this would be a breaking change.

**Comment by cbundy** [comment]
Yes, agree with your idea of optional path. Probably not too common and avoiding a breaking change is ideal.

**Comment by cbundy** [comment]
I've created a PR, would love your feedback
https://github.com/mattwebbio/orbital-sync/pull/68

**Comment by mattwebbio** [comment]
> I've created a PR https://github.com/mattwebbio/orbital-sync/pull/68 , would love your feedback

This is awesome! It looks like you've put quite a bit of time into this. I really appreciate it! I'm AFK this weekend but I'll try to look at it some time this coming week 😊

**Comment by mattwebbio** [comment]
Merged and bumped to `1.4`! Thanks again for your contribution, @cbundy :)

**Comment by cbundy** [comment]
Awesome, thanks, pleasure to work with you and happy to do it again sometime
